name: Sync upstream
on:
  workflow_dispatch:
  schedule:
    - cron: "0 2 * * *"
permissions:
  contents: write
jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Sync Singularity (Evolved)
        run: |
          git remote add upstream https://github.com/The-Anomalist/Singularity.git
          git fetch upstream Evolved
          git merge upstream/Evolved --no-edit
      - name: Sync dreamworld (staging)
        run: |
          git remote add dreamworld https://github.com/JackA1ltman/dreamworld_oneplus_sm8250.git
          git fetch dreamworld staging
          git merge dreamworld/staging --no-edit
      - run: git push origin Evolved
